- name: apply k8's configuration
  hosts: node
  become: yes
  tasks:
    - name: create new deployment
      command: kubectl apply -f /home/ubuntu/deployment.yml
      register: result
      environment:
          KUBECONFIG: /home/ubuntu/.kube/config

    - name: create new service
      command: kubectl apply -f /home/ubuntu/service.yml
      register: result
      environment:
          KUBECONFIG: /home/ubuntu/.kube/config
