apiVersion: apps/v1
kind: Deployment
metadata:
   name: devops-deploy
spec:
   replicas: 1
   selector:
       matchLabels:
          app: devops
   template:
       metadata:
          labels:          
             app: devops
       spec:
          containers:
          - name: devops-container
            image: ariharasudhanr/devops:latest
            imagePullPolicy: Always
            cresources:
          requests:
            cpu: 200m       # Reserve sufficient CPU for image pulling
            memory: 256Mi   # Reserve sufficient memory for container startup
          limits:
            cpu: 500m
            memory: 512Mi
            ports:
            - containerPort: 80
